name: App / Build ShebaMind Image

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    uses: autinno-org/frappe_docker/.github/workflows/app-build-image.yml@develop # main
    with:
      app_name: ShebaMind # shebamind
      app_repo: autinno-oss/shebamind.git
      app_ref: main #develop
      frappe_ref: version-16
      frappe_image_prefix: ghcr.io/frappe
      image_name: ghcr.io/autinno-org/frappe_docker # ghcr.io/autinno-oss/shebamind
      image_tag: shebamind # develop
      push: true
      registry: ghcr.io
      frappe_repo: https://github.com/frappe/frappe
      builder_repository: autinno-org/frappe_docker # frappe/frappe_docker
      builder_ref: develop # main
      platforms: linux/amd64
    secrets:
      APP_REPO_PAT: ${{ secrets.SHEBAMIND_REPO_PAT }}
